# Generated by Django 4.2 on 2023-04-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_remove_projectemployeetable_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectemployeetable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.projecttable', unique=True),
        ),
    ]
