# Generated by Django 4.2 on 2023-04-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_alter_projectemployeetable_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectemployeetable',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.projecttable'),
        ),
    ]
