# Generated by Django 4.2 on 2023-04-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0004_alter_projectemployeetable_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttable',
            name='leader',
        ),
        migrations.DeleteModel(
            name='ProjectEmployeeTable',
        ),
        migrations.DeleteModel(
            name='projectTable',
        ),
    ]
