# Generated by Django 4.2 on 2023-04-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeApp', '0005_remove_projecttable_leader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTable',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('startedDate', models.DateField(null=True)),
                ('description', models.TextField()),
                ('leader', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employeeApp.employeetable')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEmployeeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ManyToManyField(to='employeeApp.employeetable')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectApp.projecttable')),
            ],
        ),
    ]
