# Generated by Django 4.2 on 2023-04-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectemployeetable',
            old_name='project',
            new_name='Pid',
        ),
    ]
