# Generated by Django 4.2 on 2023-04-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0005_remove_projecttable_leader_and_more'),
        ('projectApp', '0002_rename_project_projectemployeetable_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectemployeetable',
            name='Pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectApp.projecttable'),
        ),
        migrations.AlterField(
            model_name='projectemployeetable',
            name='employee',
            field=models.ManyToManyField(null=True, to='employeeApp.employeetable'),
        ),
    ]
